config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = 'Item deleted'
    redirect_to root_path
  end

  private

  def todo_params
    params.require(:todo).permit(:item)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @todos = Todo.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lootodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% require 'date' %>

<h2>Lootodo</h2>
<h4><%= Date.today.strftime("%A, %B %d") %></h4>
<br>
<div class="row">
  <div class="col-md-6">
    <p>TODOS</p>
    <%= form_with scope: :todo, url: todos_path do |f| %>
      <%= f.text_field :item, placeholder: "Add new task" %><br>
      <br>
      <%= f.submit "+", class: "btn btn-primary" %>
    <% end %>
    <ul>
      <% @todos.each do |todo| %>
          <h3>
            <li id="list">
              <%= todo.item %> <small>🎉 50XP</small>
            <small>
              <%= link_to 'x', todo,  method: :delete %>
            </small>
            </li>
          </h3>
      <% end %>
    </ul>
  </div>
</div>